### ISSUE TITLE
Images on dockerhub and github registry not the same

### ISSUE THREAD

**Issue by akleber** [YOURLS/docker#129]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2

### Description

I noticed that the fix 4fe274d482243febfbe107557d22857941ab319f is not present in the image I pulled from dockerhub `docker pull yourls:1.8.2`, but it is present in the image I pulled from github registry `docker pull ghcr.io/yourls/yourls:1.8.2`. 

Docker shows "updated 5 days ago" (20.11.2021), Github shows "updated 6 days ago". The fix was integrated 26 days ago so it should be present in both images.
I have not looked into how the images are created or deployed, so I have no idea about the reason for this discrepancy.

### Expectation

I expect that images on Github and Dockerhub have the same content.

### Reproduction steps

To see that both images are not the same:
`docker run yourls:1.8.2` shows the error message "chown: cannot access 'wp-config.php': No such file or directory"
`docker run ghcr.io/yourls/yourls:1.8.2` does not show the error message.

**Comment by LeoColomb** [comment]
Thanks for opening this issue @akleber.
That said the behavior described is actually the one expected.

As mentioned on the README, there may be a delay between in-repo status and Docker Hub available image.
YOURLS' image on Docker Hub is build by a Docker-official building farm which is completely independent of YOURLS.
This explains the current status:
* Last commit in this repo was 6 days ago, so is the image pushed on the YOURLS org registry.
* Last change of the ref from official images repo is about a month ago or something, meaning the very latest YOURLS/docker commits are not used.
* Official images are regularly recompiled to make sure they used latest upstream images, which explains the 5 days old build.

As of today, YOURLS org' images can be seen as nightly builds from YOURLS/docker perspective, even if this might change a bit in the future to provide more granularity around Docker images.

Do you need one of the latest commit for your usage? I can trigger an ref update, let me know.

**Comment by akleber** [comment]
Thanks for your explanation I appreciate it. It's clear for me now.
I can use the YOURLS org image so an update is not needed from my side.
