### ISSUE TITLE
Docker data not persisted!

### ISSUE THREAD

**Issue by arladmin** [YOURLS/docker#158]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2

### Description

After setting up my docker instance of yourls using the standard image, i used it for a while.
Subsequently, i recreated the docker containers (```docker-compose down && docker-compose up -d```) and surprisingly, my yourls instance had not persisted.

All the data that i had created was gone and i was back to a fresh instance(install page) !

Does the official ```docker-compose.yml``` not include persistent volumes by default?
If not, what needs to be done to make sure it does?

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @arladmin.
That said, per default data in Docker is never persistent, so this is quite expected. 
If you are referring to the database, please refer to the relative docker image documentation.

**Comment by LeoColomb** [comment]
@arladmin 

> Was expecting the `docker-compose.yml` to be 'production-ready'

Which file are you referring to? The "Getting started" template example given on the Docker Hub page? 
As clearly stated, it is a template example...

> Shouldn't that be persisted as well?

What are you referring to? What data should be persisted?

**Comment by arladmin** [comment]
> Which file are you referring to?

The one mentioned here:
https://hub.docker.com/_/yourls/


> What are you referring to? What data should be persisted?

If i recreate ( ```docker-compose down && docker-compose up -d ``` ) the docker containers, the yourls instance loses its configuration and reverts to a fresh install state.
How to correct this to the instance state being persisted?

**Comment by LeoColomb** [comment]
> The one mentioned here: [hub.docker.com/_/yourls](https://hub.docker.com/_/yourls/)

Yes, the one shown as example on Docker Hub. So yes it is an example.

> How to correct this to the instance state being persisted?

We cannot answer this if you don't answer my previous question: what data specifically do you expect to be persisted?

**Comment by lyh16** [comment]
I'm taking a guess at what you're wanting here. But if my guess is right and you want to persist the configs/data for both the "yourls" and "mysql" services, you can take a look at this "docker-compose.yml" file which I am using right now. I referred to multiple sources to write up this file.

<pre>
version: '3.1'
services:
  yourls:
    depends_on:
      - mysql
    image: yourls
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./yourls_user:/var/www/html/user
    environment:
      - YOURLS_DB_PASS=${YOURLS_DB_PASS}
      - YOURLS_SITE=${YOURLS_SITE}
      - YOURLS_USER=${YOURLS_USER}
      - YOURLS_PASS=${YOURLS_PASS}
      - YOURLS_URL_CONVERT=62
      - YOURLS_COOKIEKEY=${YOURLS_COOKIEKEY}

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${YOURLS_DB_PASS}
      - MYSQL_DATABASE=yourls
    volumes:
      - db_data:/var/lib/mysql

# You should use persistant storage for this,
# as if the volume is deleted, everything is gone!
volumes:
  db_data:
</pre>

The data for yourls will be persisted in the "yourls_user" directory with all the "config.php" customizations you make. And the mysql data will be persisted in the "db_data" volume. Create a ".env" file containing the necessary values for the environment variables of your choice and you are set to go.

You can also choose between docker bind mounts and volumes, whichever fits you the best.
A simple and intuitive explanation for understanding the difference between the two: https://maximorlov.com/docker-compose-syntax-volume-or-bind-mount/
Docker offical docs: https://docs.docker.com/storage/
