### ISSUE TITLE
"&" in the password bricks the config file (docker)

### ISSUE THREAD

**Issue by JustinGuese** [YOURLS/docker#164]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

latest

### Description

inserting a password with "&" in the "YOURLS_PASS" as environment variable messes up the config file 

```
yourls_user_passwords = [
    'user' => 'passwordwithoutand getenv_docker('YOURLS_USER') => getenv_docker('YOURLS_PASS'),',
];
```

### Expectation

i guess the & is actually interpreted

### Reproduction steps

set password YOURLS_PASS = sjkdhaadjsk&

### Context

should be fixed/escaped

**Comment by LeoColomb** [comment]
Thanks for opening the ticket @JustinGuese.
I can reproduce, indeed.
The behavior is caused by the sed command on the entrypoint. 
https://github.com/YOURLS/docker/blob/2dec68f8872e6634020c3795e1f87504a4a65c22/docker-entrypoint.sh#L80

**Comment by LeoColomb** [comment]
This change should do the trick: [`10a7a68` (#165)](https://github.com/YOURLS/docker/pull/165/commits/10a7a68dffa6053b2361e916a8559a56ec30f2e3)
Do you confirm?

**Comment by ozh** [comment]
@LeoColomb would it be simpler and make sense if we checked for YOURLS_USER and YOURLS_PASS env var in YOURLS/YOURLS itself ?

**Comment by LeoColomb** [comment]
@ozh I honestly have no opinion on this point. 
That being said, it could be weird to have YOURLS checking the env for only 2 variables. And might raise a case for its volatility.

**Comment by JustinGuese** [comment]
@LeoColomb should work as a "quickfix". i mean it's a rare case, so probably not causing too much trouble
