### ISSUE TITLE
Error setting `USER` in `Dockerfile`

### ISSUE THREAD

**Issue by rfashwall** [YOURLS/docker#177]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

We are creating our own image using the base image `yourls:1.9-apache`.
We have added a custom shell script as our entry point that do the following:
- install custom plugins we need
- copy our own custom config from a mounted volume created 
- execute `docker-entrypoint` the entry point for base image

### Expectation

We have a job that check dockerfile and image for vulnerabilities, and we need to set a user inside the dockerfile since it is not recommended to use root user in the container.

Installation of yourls should be using root user and after done we should be able to set a user with non root permissions.

### Reproduction steps

- create a new dockerfile with base `yourls:1.9-apache`.
- set USER in the dockerfile to `www-data`
- build the docker image and run

#### Error 
Installation of yourls will not be possible due to the error `Cannot mkdir: No space left on device`

**Comment by LeoColomb** [comment]
Thanks for opening this issue @rfashwall.
That said the error reposted is a quite clear error from the host:
> No space left on device

If it'd be an issue with permissions or something, the error would be different.

Have you tried without this user change?
Are you absolutely sure the _is_ space left on your system for the container to run?

**Comment by rfashwall** [comment]
@LeoColomb Thank you for your reply,
Without setting the user in the dockerfile, it works just fine, but the user will be root and running the container as root brings a lot of risks. 
The error occurs when we set the user in the dockerfile to  `www-data` to have least privilege container.

**Comment by LeoColomb** [comment]
Thanks for your reply @rfashwall. 
That said your answer doesn't help to understand the complete context, especially regarding the significant customization of the image. 
Please elaborate where exactly this error is raised and why the error is about disk space and not permissions.

**Comment by rfashwall** [comment]
@LeoColomb thank you for your help. this issue is solved by setting the user and the target group in the dockerfile as below:
```
FROM yourls:1.9-apache

COPY custom-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["bash","custom-entrypoint.sh"]

RUN adduser www-data www-data

USER www-data
```
