### ISSUE TITLE
Latest Github Expiry plugin not working with latest version of YOURLS

### ISSUE THREAD

**Issue by MKDan** [YOURLS/docker#185]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

The latest Github Expiry plugin (https://github.com/joshp23/YOURLS-Expiry) not working with the latest version of YOURLS 1.9.1

The installation is a fresh installation of both.

The options appear - [blob:https://imgur.com/560d9baa-22a9-4bfe-bf0c-ab3ab2fa9491](https://i.imgur.com/RU5pkNw.png)

But the link has no expiry.

### Expectation

 I want only expiring link URLs to be created, by anyone without signing up, registered users can have options to see stats and delete links (but others can't).

### Reproduction steps

Install both and check if they work.

### Context

The latest Github Expiry plugin (https://github.com/joshp23/YOURLS-Expiry) as of 18th July is not working with the latest version of YOURLS 1.9.1

**Comment by dgw** [comment]
This isn't a YOURLS issue. See joshp23/YOURLS-Expiry#40
